### ISSUE TITLE
Support PromiseLike with `flow()`

### ISSUE THREAD

**Issue by kav** [mobxjs/mobx-state-tree#1817]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
When using supabase with MST and flow the flow type seems to get hung up on supabase's use of PromiseLike rather than Promise for their postgrest-js library
https://github.com/supabase/postgrest-js/blob/06946baf852b42f04b55e10ec900216f5ceeada7/src/lib/types.ts#L51

**Describe the solution you'd like**
Replace the use of Promise in flow() with PromiseLike, or perhaps add an alternative flow function? Maybe consider extending the generic to include the promise type? Not really sure what's best here happy to take any suggestions.

**Describe alternatives you've considered**

Wrap the PromiseLike in a Promise or patch the package directly. Encourage supabase to move from PromiseLike to the full Promise interface.

**Additional context**

**Are you willing to (attempt) a PR?**
* [x] Yes
* [ ] No

**Comment by 10000multiplier** [comment]
@kav Sir, I beg you to release this PR. 
![image](https://user-images.githubusercontent.com/57633368/147803934-a53903e1-b8d0-42af-93cf-6d4573b67784.png)

**Comment by 10000multiplier** [comment]
@kav just tried applying your fix with patch-package and still getting hung on how to make it work with supabase.

Would you be so kind as to post a little code snippet of what works for you?

**Comment by kav** [comment]
Here's an example of how we were using it in an action:
```typescript
getCategories: flow(function* () {
  const { supabase } = self.environment;
  const { data, error }: { data: CategorySnapshot[]; error: Error } = yield supabase
    .from('categories')
    .select()
    .order('sortkey');
  if (error) throw error;
  // save or return or what have you
  ...
```

**Comment by jamonholmgren** [comment]
Fixed in 5.1.1 -- thanks @kav!

https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.1.1

**Comment by djMax** [comment]
This really seems like it should've been a major version bump. It breaks existing implementations quite soundly.

**Comment by EmilTholin** [comment]
I'm not sure the consequences of this change has been thought through all the way. `PromiseLike` only has `then`, [so code like this now throws an error](https://codesandbox.io/s/heuristic-maxwell-zy7c9?file=/src/index.ts):

```ts
import { flow, types } from "mobx-state-tree";

const getNum = (): Promise<number> => {
  return new Promise((resolve, reject) => {
    if (Math.random() < 0.5) {
      resolve(1);
    } else {
      reject("Failed to get num");
    }
  });
};

const Store = types
  .model({
    num: 0
  })
  .actions((self) => ({
    fetchNum: flow(function* () {
      try {
        const num = yield getNum();
        self.num = num;
      } catch (error) {
        throw error;
      }
    })
  }));

const store = Store.create();

store
  .fetchNum()
  .then((result) => console.log("fetched num"))
  // Parameter 'error' implicitly has an 'any' type.
  .catch((error) => console.error(error));
```
Is there any way we can revert this change and still have the users of MST use e.g. the Supabase API?

**Comment by kav** [comment]
So sorry, I've gotten so used to using async/await; it didn't occur to me to test pure promise syntax and I absolutely spaced on that, fairly basic, case. You could resolve it (ha) by passing the catch function as the second parameter to then but that would definitely be a breaking change.

**Comment by EmilTholin** [comment]
No worries. Could you show a `postgres-js` example that doesn't work with the previous `Promise` type implementation? I would personally prefer if we go back to the `Promise` type rather than using the `PromiseLike` type and skip the breaking change, but we should of course try to fix the original issue.

**Comment by kav** [comment]
This example fails with the error on the `flow` call with Promise. It's likely we can make a smaller change with a well placed `Promise<T> | PromiseLike<T>`. Let me see what I can do:
Here's the unified examplee case
```ts
import { createClient } from "@supabase/supabase-js"
import { flow, types } from "mobx-state-tree"

const getNum = (): Promise<number> => {
  return new Promise((resolve, reject) => {
    if (Math.random() < 0.5) {
      resolve(1)
    } else {
      reject("Failed to get num")
    }
  })
}

const Store = types
  .model({
    num: 0,
  })
  .actions((self) => ({
    fetchNum: flow(function* () {
      try {
        const num = yield getNum()
        self.num = num
      } catch (error) {
        throw error
      }
    }),
    // Argument of type '() => Generator<PostgrestFilterBuilder<any>, any, { data: any; error: any; }>' is not assignable to parameter of type '() => Generator<Promise<any>, any, any>'.
    // Call signature return types 'Generator<PostgrestFilterBuilder<any>, any, { data: any; error: any; }>' and 'Generator<Promise<any>, any, any>' are incompatible.
    //   The types returned by 'next(...)' are incompatible between these types.
    //     Type 'IteratorResult<PostgrestFilterBuilder<any>, any>' is not assignable to type 'IteratorResult<Promise<any>, any>'.
    //       Type 'IteratorYieldResult<PostgrestFilterBuilder<any>>' is not assignable to type 'IteratorResult<Promise<any>, any>'.
    //         Type 'IteratorYieldResult<PostgrestFilterBuilder<any>>' is not assignable to type 'IteratorYieldResult<Promise<any>>'.
    //           Type 'PostgrestFilterBuilder<any>' is not assignable to type 'Promise<any>'.
    fetchRecord: flow(function* () {
      const supabase = createClient(
        "<a supabase project url>",
        "<a supabase key>"
      )
      const { data, error } = yield supabase
        .from("<a table>")
        .select()
      if (error) throw error
      return data
    }),
  }))

const store = Store.create()

store
  .fetchNum()
  .then((result) => console.log("fetched num"))
  // Property 'catch' does not exist on type 'PromiseLike<void>'.
  .catch((error) => console.error(error))

store.fetchRecord().then((result) => console.log("fetched record"))
```

**Comment by kav** [comment]
#1871  works with the above though I'd love a confirmation

**Comment by jamonholmgren** [comment]
Released #1871 as 5.1.3. Apologies for this!

**Comment by jamonholmgren** [comment]
I've also deprecated 5.1.1 and 5.1.2 (which are identical due to a publishing snafu).
